### ISSUE TITLE
Some inconsistant results

### ISSUE THREAD

**Issue by Flashpok** [NEDb-tk/deemix-foobar2000#11]
Hi, 
thank you for your work ! 

Somes requests have no results and I don't understant because I find result if I do a Deezer research.

foobar.txt : "Hyukoh/20/01 - Lonely.flac"
strip.txt : Hyukoh/20/01/Lonely
links.txt : Couldn't Find Album: Hyukoh/20/01/Lonely
Next line in links.txt : https://www.deezer.com/track/401475222 - Hyukoh/20/01/Lonely

But it's an error. The correct link to the track is : https://www.deezer.com/us/track/625401032

Any idea ?

**Comment by NEDb-tk** [comment]
Thanks for hanging on. As stated earlier, this script is kinda prone to errors (its still in development). So you're like a beta tester. That's why you are encountering so many errors! Thanks a lot for helping the development of it. I think this error occurs when the album name is a number. In `Hyukoh/20/01/Lonely`, 

`Hyukon` - Artist
`20` - Album (but is being treated as the track number)
`01` - Track Number
`Lonely` - Title (but is being treated as the album)

**Comment by NEDb-tk** [comment]
I think the issue is resolved. All I did was add change 
`if track_2d in strip:` and `elif track_3d in strip:`  to
`if track_2d in strip[2]:` and `elif track_3d in strip[2]:`

**Comment by Flashpok** [comment]
I think this not resolved  : 

First error (it stops the script) : 

foobar.txt : "ARTIST/ALBUM 1975-1980/01 - SONGTITLE.flac"
strip.txt :ARTIST/ALBUM 1975-1980/01/SONGTITLE

error message : 
`Traceback (most recent call last):
  File "main9.py", line 40, in <module>
    strip.remove(track_2d)
ValueError: list.remove(x): x not in list

Process finished with exit code 1
`
