### ISSUE TITLE
Request about track becomes album's request (no result)

### ISSUE THREAD

**Issue by Flashpok** [NEDb-tk/deemix-foobar2000#12]
foobar.txt : 

`"Medeski Martin & Wood/20/02 - Shackman.flac"`

strip.txt : 

`Medeski Martin & Wood/20/02/Shackman`

link.txt : 

`Couldn't Find Album: Medeski Martin & Wood/20/02/Shackman`

-> What's the problem ? Because the name of album is a number ? ("20"). Does it broke anything in your track search ?

**Comment by NEDb-tk** [comment]
Didn't expect a number as an album... Yes, the script is confusing the album as the track number.
The script is removing the album as it thinks its the track number. And is using the track name (`"Shackman"`) as the album.

**Comment by NEDb-tk** [comment]
> 
> 
> I think the issue is resolved. All I did was add change
> `if track_2d in strip:` and `elif track_3d in strip:` to
> `if track_2d in strip[2]:` and `elif track_3d in strip[2]:`

**Comment by Flashpok** [comment]
thank you !  I ll try today !

**Comment by Flashpok** [comment]
I think it broke the request in some conditions. For example if there is a number in title ("16 basbar" is the track title) : 

"Artist/Album/TrackNumber - 16 basbar.flac"

Error message : 
```
Traceback (most recent call last):
  File main8.py", line 41, in <module>
    strip.remove(track_2d)
ValueError: list.remove(x): x not in list
```

**Comment by NEDb-tk** [comment]
I think the problem should be solved. I tested it out a few times, and all seems to work. I forgot to add a break to the while loops for the track number.

```
		if track_2d in strip[2]:
			strip.remove(track_2d)
			break
```

That should do it.

**Comment by Flashpok** [comment]
I think this is not resolved  : 

First error (it stops the script) : 

foobar.txt : "ARTIST/ALBUM 1975-1980/01 - SONGTITLE.flac"
strip.txt :ARTIST/ALBUM 1975-1980/01/SONGTITLE

error message : 
````
Traceback (most recent call last):
  File "main9.py", line 40, in <module>
    strip.remove(track_2d)
ValueError: list.remove(x): x not in list

Process finished with exit code 1
````

**Comment by Flashpok** [comment]
Optimist word : On the last version of the script (until it's broke with the precedent error) : 
Total lines (.Flac tracks) in foobar.txt : 1285
1228 lines  : -> correct link for track (YES!)
52 lines : Album founded (I don't know if there are all correct. I can check some ones. I'll check to understand why tracks don't match)
2 lines : Couldn't find track 

Bravo!

**Comment by NEDb-tk** [comment]
Sorry its been a bit. Ill take a look into that error. Thanks for your patients!

**Comment by NEDb-tk** [comment]
I am going to close this issue and create a new one. This issue is getting rather long.
