### ISSUE TITLE
Some problem with "/" inside album AND in title variable

### ISSUE THREAD

**Issue by Flashpok** [NEDb-tk/deemix-foobar2000#8]
(I move this topic here)

Some problem with "/" inside album AND in title variable : It brokes track results. 

first example (track): 

`Artist/Album/NumberTrack/Title of the track **/** and second part of title of the track (and perhaps / thirth part of title)`

Second example (album) : 

`Artist Part1 / Artist Part 2/Album/NumberTrack/Title of the track `

Is it possible to replace "/" by " " in each of them ?

**Comment by NEDb-tk** [comment]
It'll be possible. We will just assume that all items in the list after `['NumberTrack']` is gonna be the title. 
`['Artist Part1',  'Artist Part 2', 'Album', 'NumberTrack', 'Title', 'of', 'the', 'track']`

**Comment by NEDb-tk** [comment]
I will be updating `main.py` tomorrow. Thanks for your patients!

**Comment by Flashpok** [comment]
Thank you !!

**Comment by NEDb-tk** [comment]
Should be fixed!

**Comment by Flashpok** [comment]
I don't think it's fixed.

Example : 

foobar.txt : 

`"Alvin Lee/On the Road to Freedom (Remastered Bonus Track Version)/13 - So Sad (No Love of His Own) (Bonus Track - Single Version - Remastered).flac"`

Strip.txt : 
`Alvin Lee/On the Road to Freedom (Remastered Bonus Track Version)/13/So Sad (No Love of His Own) (Bonus Track/Single Version/Remastered)`

-> "-" is replaced by "/". It's correct for "/13/" but not for the nexts. It brokes track research.

links.txt : 
`https://www.deezer.com/album/6544900 - Alvin Lee/On the Road to Freedom (Remastered Bonus Track Version)/13/So Sad (No Love of His Own) (Bonus Track/Single Version/Remastered)`

-> Mistake : Request is about a track, not album.
